# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDateaccepted1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dateaccepted1(self):
    self.driver.get("http://localhost/moodle/course/edit.php?id=3&returnto=catmanage")
    self.driver.set_window_size(622, 732)
    self.driver.find_element(By.ID, "id_startdate_day").click()
    dropdown = self.driver.find_element(By.ID, "id_startdate_day")
    dropdown.find_element(By.XPATH, "//option[. = '16']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_startdate_day > option:nth-child(16)").click()
    self.driver.find_element(By.ID, "id_startdate_month").click()
    dropdown = self.driver.find_element(By.ID, "id_startdate_month")
    dropdown.find_element(By.XPATH, "//option[. = 'October']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_startdate_month > option:nth-child(10)").click()
    value = self.driver.find_element(By.ID, "id_startdate_month").get_attribute("value")
    assert value == "10"
    self.vars["final_month"] = self.driver.find_element(By.ID, "id_startdate_month").get_attribute("value")
  
